# Generated by Django 5.0.3 on 2024-05-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROLES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.roles')),
            ],
        ),
    ]
