# Generated by Django 5.0.3 on 2024-05-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employees',
        ),
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='scan.roles'),
        ),
    ]
