# Generated by Django 5.0.3 on 2024-05-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_companyoutlet_activityemployees'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(default='in', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='activityemployees',
            name='checkin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='act_log', to='scan.checkintype'),
        ),
    ]
