# Generated by Django 5.0.3 on 2024-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_rename_activityemployees_activityemployee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='12345', max_length=200),
        ),
    ]
