# Generated by Django 5.0.3 on 2024-05-17 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_rename_time_activityemployee_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityemployee',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='activityemployee',
            name='duration',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='scan.companyoutlet'),
        ),
        migrations.AlterField(
            model_name='activityemployee',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
