# Generated by Django 5.0.3 on 2024-05-17 01:23

import scan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_remove_activityemployee_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityemployee',
            name='checkin_type',
        ),
        migrations.AddField(
            model_name='activityemployee',
            name='type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default=scan.models.CheckinTypeEnum['IN']),
        ),
        migrations.DeleteModel(
            name='CheckinType',
        ),
    ]
