# Generated by Django 5.0.3 on 2024-05-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_remove_activityemployee_checkin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityemployee',
            name='type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN'),
        ),
    ]
