# Generated by Django 5.0.3 on 2024-05-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0011_remove_activityemployee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityemployee',
            name='types',
            field=models.CharField(choices=[('check_in', 'IN'), ('check_out', 'OUT')], default='IN'),
        ),
    ]
