# Generated by Django 5.0.3 on 2024-05-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0012_activityemployee_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='types',
            new_name='type',
        ),
    ]
