# Generated by Django 5.0.3 on 2024-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0013_rename_types_roles_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityemployee',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityemployee',
            name='types',
            field=models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], default='IN', max_length=5),
        ),
    ]
