# Generated by Django 5.0.3 on 2024-05-17 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0016_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 5, 18, 3, 23, 51, 299349), max_length=200),
        ),
    ]
