# Generated by Django 5.0.3 on 2024-05-17 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0020_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityemployee',
            name='lati',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='activityemployee',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyoutlet',
            name='lati',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='companyoutlet',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=20, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 5, 18, 4, 24, 45, 380442), max_length=200),
        ),
    ]
