# Generated by Django 5.0.3 on 2024-05-18 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0022_alter_employee_username_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='user',
            new_name='emp_id',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 5, 18, 12, 45, 51, 344033), max_length=200),
        ),
    ]
