# Generated by Django 5.0.3 on 2024-05-18 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0023_rename_user_accesstoken_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='refresh',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activityemployee',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 5, 19, 6, 39, 23, 648203), max_length=200),
        ),
    ]
